#version 460
#include "../extensions.glsl"
#include "../common.glsl"
#include "swizzle.glsl"

layout(constant_id = NUM_GLOBAL_CONSTANTS) const uint DEBUG_WRITE_PATCHES = 0;

layout(local_size_x = 32, local_size_y = 32) in;

layout(push_constant) uniform PatchGradientsPc {
    ExtremumLocations extremum_locations;
    KeypointIndices keypoints;
    PatchBuffer patch_gradients;
    uint image_width;
    uint image_height;
    float patch_scale_factor;

};

const uint KERNEL_RAD = 2;
const uint KERNEL_SIZE = 2 * KERNEL_RAD + 1;
const float gauss_kernel[KERNEL_SIZE] = {
        0.0096,
        0.2054,
        0.5699,
        0.2054,
        0.0096
    };

shared float sh_patch[PATCH_SIZE * PATCH_SIZE];

shared float sh_blur_tmp[PATCH_SIZE * PATCH_SIZE];

void main() {
    const uint patch_index = gl_WorkGroupID.x;
    if (patch_index >= min(MAX_KEYPOINTS, keypoints.n_keypoints)) {
        return;
    }
    const uint local_x = gl_LocalInvocationID.x;
    const uint local_y = gl_LocalInvocationID.y;

    const uint kp_loc_idx = keypoints.data[patch_index];
    const float scale = get_extremum_scale_float(extremum_locations, kp_loc_idx) * patch_scale_factor;
    const float kp_scale_level = floor(log2(scale));

    const float patch_x = get_extremum_x_float(extremum_locations, kp_loc_idx);
    const float patch_y = get_extremum_y_float(extremum_locations, kp_loc_idx);
    const float patch_angle = radians(uintBitsToFloat(keypoints.data[MAX_KEYPOINTS + patch_index]));

    {
        const vec2 texture_size = textureSize(TEXTURE_PATCH_PYR, 0);
        const float ps2 = float(PATCH_SIZE) / 2.0;
        const float xx = (float(local_x) - ps2) * cos(patch_angle) - (float(local_y) - ps2) * sin(patch_angle);
        const float yy = (float(local_x) - ps2) * sin(patch_angle) + (float(local_y) - ps2) * cos(patch_angle);
        const float sample_x = xx + patch_x;
        const float sample_y = yy + patch_y;
        if (kp_scale_level == 0) {
            sh_patch[local_y * PATCH_SIZE + local_x] = texture(
                sampler2DArray(texture_coarse, SAMPLER_BIL),
                vec3((sample_x + 0.5) / texture_size.x, (sample_y + 0.5) / texture_size.y, 0)
            ).r;
        } else {
            sh_patch[local_y * PATCH_SIZE + local_x] = textureLod(
                sampler2D(TEXTURE_PATCH_PYR, SAMPLER_BIL),
                vec2(sample_x + 0.5, sample_y + 0.5)/ texture_size,
                // No real justification for the -1 here. Seems to work quite well,
                // but no comprehensive testing. 
                // More aliasing (-1 means subsampling 2x higher res layer) can lead to better matching
                // on easy/very similar images since it kind of sharpens/reinforces patterns
                // in almost identical ways in both images. But could definitely be different
                // in the general case.
                kp_scale_level - 1
            ).r;
        }
        if (DEBUG_WRITE_PATCHES == 1) {
            const uint idx = local_y * PATCH_SIZE + local_x;
            patch_gradients.patches[2 * MAX_KEYPOINTS + patch_index].data[idx] = sh_patch[idx];
        }
        barrier();
    }

    {
        // vertical blur pass
        float sum = 0;
        for (int i = 0; i < KERNEL_SIZE; i++) {
            const int yy = clamp(int(local_y) + i - int(KERNEL_RAD), 0, int(PATCH_SIZE) - 1);
            sum += gauss_kernel[i] * sh_patch[yy * PATCH_SIZE + local_x];
        }
        sh_blur_tmp[local_y * PATCH_SIZE + local_x] = sum;
        barrier();
    }

    {
        // horizontal blur pass
        float sum = 0;
        for (int i = 0; i < KERNEL_SIZE; i++) {
            const int xx = clamp(int(local_x) + i - int(KERNEL_RAD), 0, int(PATCH_SIZE) - 1);
            sum += gauss_kernel[i] * sh_blur_tmp[local_y * PATCH_SIZE + xx];
        }
        sh_patch[local_y * PATCH_SIZE + local_x] = sum;
        barrier();
    }

    const float grad_x =
        sh_patch[local_y * PATCH_SIZE + clamp(local_x, 1, PATCH_SIZE - 1) - 1] - sh_patch[local_y * PATCH_SIZE + clamp(local_x, 0, PATCH_SIZE - 2) + 1];
    const float grad_y = sh_patch[(clamp(local_y, 0, PATCH_SIZE - 2) + 1) * PATCH_SIZE + local_x] - sh_patch[(clamp(local_y, 1, PATCH_SIZE - 1) - 1) * PATCH_SIZE + local_x];
    
    const float EPS = 1e-8;
    // sqrt pulled out from embed_gradients
    const float mag = sqrt(sqrt(grad_x * grad_x + grad_y * grad_y + EPS));
    const float angle = -atan(grad_y, grad_x);

    const uint out_index = swizzled_index(local_x, local_y);
    ASSERT(unswizzle_index(out_index) == uvec2(local_x, local_y));
    patch_gradients.patches[patch_index].data[out_index] = mag;
    patch_gradients.patches[MAX_KEYPOINTS + patch_index].data[out_index] = angle;
}
