#version 460
#include "extensions.glsl"
#include "common.glsl"
#include "conv_pushconstants.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

const float KERNEL[] = { 6.0/16.0, 4.0/16.0, 1.0/16.0 };

float sampleCoarse(vec2 coords) {
    return texture(sampler2DArray(texture_coarse, SAMPLER_BIL), vec3(coords.x, coords.y, in_level)).r;
}

float sampleScratch(vec2 coords) {
    return texture(sampler2D(TEXTURE_SCRATCH, SAMPLER_BIL), coords).r;
}

void main() {
    const uint texture_width = textureSize(texture_coarse, 0).x;
    const uint texture_height = textureSize(texture_coarse, 0).y;

    const uint x = gl_GlobalInvocationID.x;
    const uint y = gl_GlobalInvocationID.y;

    if (gl_GlobalInvocationID.x >= width || gl_GlobalInvocationID.y >= height) {
        return;
    }

    const float x_in = (float(x) + 0.5) / float(texture_width);
    const float y_in = (float(y) + 0.5) / float(texture_height);
    const vec2 coords_in = vec2(x_in, y_in);

    if (vertical_pass) {
        const float dilate = float(1 << in_level) / float(texture_height);
        float sum = sampleScratch(coords_in).r * KERNEL[0];
        sum += sampleScratch(coords_in - vec2(0, dilate * 1)).r * KERNEL[1];
        sum += sampleScratch(coords_in - vec2(0, dilate * 2)).r * KERNEL[2];

        sum += sampleScratch(coords_in + vec2(0, dilate * 2)).r * KERNEL[2];
        sum += sampleScratch(coords_in + vec2(0, dilate * 1)).r * KERNEL[1];

        imageStore(image_coarse, ivec3(x, y, in_level + 1), vec4_FORMAT(sum, 0.0, 0.0, 1.0));

    } else {
        const float dilate = float(1 << in_level) / float(texture_width);
        float sum = sampleCoarse(coords_in).r * KERNEL[0];
        sum += sampleCoarse(coords_in - vec2(dilate * 2, 0)).r * KERNEL[2];
        sum += sampleCoarse(coords_in - vec2(dilate * 1, 0)).r * KERNEL[1];

        sum += sampleCoarse(coords_in + vec2(dilate * 1, 0)).r * KERNEL[1];
        sum += sampleCoarse(coords_in + vec2(dilate * 2, 0)).r * KERNEL[2];

        imageStore(IMAGE_SCRATCH, ivec2(x, y), vec4_FORMAT(sum, 0.0, 0.0, 1.0));
    }
}

